---
- hosts: ansible
  gather_facts: yes
  
  tasks:
   - name: Update apache version ---yum
     yum: name=httpd state=present
     when: ansible_pkg_mgr == 'yum'
     notify: restart httpd

   - name: Update apache version ---apt
     apt: name=apache2 state=present update_cache=yes
     when: ansible_pkg_mgr == 'apt'
     notify: restart apache

  handlers:
   - name: restart httpd
     service: name=httpd state=restarted
  handlers:
   - name: restart apache
     service: name=apache2 state=restarted
